foreground #dcdccc
background #2c2c2c

color0 #3f3f3f
color8 #709080

color9 #705050
color1 #dca3a3

color10 #60b48a
color2 #72d5a3

color11 #dfaf8f
color3 #f0dfaf

color12 #9ab8d7
color4 #94bff3

color5 #dc8cc3
color13 #ec93d3

color14 #8cd0d3
color6 #93e0e3

color15 #dcdccc
color7 #ffffff
